### PR TITLE
Simple comment fix

### PR DESCRIPTION
**Pull request by sazid**

### CODE REVIEW

**Comment by sazid** [comment]
I need a bit of your help regarding how you use <paper-input>. In my current realtime app, I cannot directly use `<paper-input>` element as it creates something called #shadow and then creates a `<textarea>` inside `<paper-input>` element.

**Comment by sethmiles** [comment]
Hey Mohammed, sorry for the delay! The realtime app depends on polymer (see
www.polymer-project.org) and uses the shadow dom to create modular
elements, such as the <paper-input> element. You'll notice that in
components/paper-input/paper-input.html is a template for what the html
content (the textarea you're referring to) for a <paper-input> element
should look like. These components were built by the polymer team. Anything
inside the elements directory are custom elements that I have made.

If you give me a good description of what the issue is I can provide some
more direction. Hope this helps!

On Sun, Oct 19, 2014 at 11:21 AM, Mohammed Sazid-Al-Rashid <
notifications@github.com> wrote:

> I need a bit of your help regarding how you use . In my current realtime
> app, I cannot directly use <paper-input> element as it creates something
> called #shadow and then creates a <textarea> inside <paper-input> element.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sethhoward1988/polymer-realtime-playground/pull/1#issuecomment-59656938
> .

## 

Seth

**Comment by sazid** [comment]
@sethhoward1988 Here's a sample code from what I'm doing:

``` js
function onFileLoaded(doc) {
    var string = doc.getModel().getRoot().get('text');

    // Keeping one box updated with a String binder.
    var docTextInput = document.getElementById('document_input');
    // var docTextInput = $('#document_input');
    gapi.drive.realtime.databinding.bindString(string, docTextInput);
    // ........
}
```

``` html
<textarea id="document_input" rows="8" placeholder="Type something..."></textarea>
```

The above code works, only if it's a `<textarea>`. But, as I replace the `<textarea>` with a `<paper-input>` element, I keep getting errors, because, the `<paper-input>` itself is not the input box, rather there is another `<textarea>` inside the shadow DOM, which I'm not being able to access.

``` html
<paper-input id="document_input" multiline label="Type something..."></paper-input>
```

Is there any way, I can get access to the `<textarea>` inside the `<paper-input>` element?
Thanks for taking the time :)

**Comment by sethmiles** [comment]
No problem, love to help.

The way polymer works is to treat the <paper-input> element as it's own element, and not need to worry about the underlying html. So, here's how to get access to the value (or the content inside the underlying textarea).

``` js
var content = document.querySelector('document_input').value
// or
var content = document.querySelector('document_input').inputValue

// update the collaborative string
doc.getModel().getRoot().get('text').setText(content);
```

If you need to set up listeners on the paper input, use the polymer bindings like below.

``` html
<paper-input id="document_input" on-click="{{ onPaperInputClick }}"
      on-keyup="{{ onPaperInputKeyup }}"></paper-input>

<script>
Polymer({
    onPaperInputClick: function () {
         var value = this.$.document_input.value
         // do something with this value
    },

    onPaperInputKeyup: function () {
         var value = this.$.document_input.inputValue
         // do something - keep in mind that you need to use inputValue if they 
         // haven't blurred the input yet. The value property only gets updated
         // once the user blurs the field.
    }
})
</script>
```

If you're planning on using the realtime api for a project, please let me know! I'm an engineer on the realtime api and would like to learn more about your project.

Thanks and hope this helps!

Also, in case you didn't know, check out this sample app live at https://realtimeplayground.appspot.com.

**Pull request merged**
